// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS0r4gMJvdlBMftsFEgETUPjfqgEnACQQ',
    appId: '1:388203201368:web:e2491fa21156ec36785b2d',
    messagingSenderId: '388203201368',
    projectId: 'nksereke-41f90',
    authDomain: 'nksereke-41f90.firebaseapp.com',
    storageBucket: 'nksereke-41f90.firebasestorage.app',
    measurementId: 'G-Y60BCDCQ04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC46m-yl64r1LnyhkH8LTGQrviW-EckpOU',
    appId: '1:388203201368:android:1953b583bdc6b38c785b2d',
    messagingSenderId: '388203201368',
    projectId: 'nksereke-41f90',
    storageBucket: 'nksereke-41f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYs3tKwU6TGBrAIPYpqIvX5mhqIQEyEp8',
    appId: '1:388203201368:ios:99200a054edccda3785b2d',
    messagingSenderId: '388203201368',
    projectId: 'nksereke-41f90',
    storageBucket: 'nksereke-41f90.firebasestorage.app',
    iosBundleId: 'com.ctl.user.ctluser',
  );
}
